/* created by Paweł Rapacz https://github.com/pawelrapacz */

#ifndef WIN_CONSOLE_COLORS_H
#define WIN_CONSOLE_COLORS_H

// Naming: FOREGROUND_BACKGROUND
#define BLACK_BLACK                   0x00
#define BLUE_BLACK                    0x01
#define GREEN_BLACK                   0x02
#define AQUA_BLACK                    0x03
#define RED_BLACK                     0x04
#define PURPLE_BLACK                  0x05
#define YELLOW_BLACK                  0x06
#define WHITE_BLACK                   0x07
#define GREY_BLACK                    0x08
#define LIGHTBLUE_BLACK               0x09
#define LIGHTGREEN_BLACK              0x0a
#define LIGHTAQUA_BLACK               0x0b
#define LIGHTRED_BLACK                0x0c
#define LIGHTPURPLE_BLACK             0x0d
#define LIGHTYELLOW_BLACK             0x0e
#define BRIGHTWHITE_BLACK             0x0f
#define BLACK_BLUE                    0x10
#define BLUE_BLUE                     0x11
#define GREEN_BLUE                    0x12
#define AQUA_BLUE                     0x13
#define RED_BLUE                      0x14
#define PURPLE_BLUE                   0x15
#define YELLOW_BLUE                   0x16
#define WHITE_BLUE                    0x17
#define GREY_BLUE                     0x18
#define LIGHTBLUE_BLUE                0x19
#define LIGHTGREEN_BLUE               0x1a
#define LIGHTAQUA_BLUE                0x1b
#define LIGHTRED_BLUE                 0x1c
#define LIGHTPURPLE_BLUE              0x1d
#define LIGHTYELLOW_BLUE              0x1e
#define BRIGHTWHITE_BLUE              0x1f
#define BLACK_GREEN                   0x20
#define BLUE_GREEN                    0x21
#define GREEN_GREEN                   0x22
#define AQUA_GREEN                    0x23
#define RED_GREEN                     0x24
#define PURPLE_GREEN                  0x25
#define YELLOW_GREEN                  0x26
#define WHITE_GREEN                   0x27
#define GREY_GREEN                    0x28
#define LIGHTBLUE_GREEN               0x29
#define LIGHTGREEN_GREEN              0x2a
#define LIGHTAQUA_GREEN               0x2b
#define LIGHTRED_GREEN                0x2c
#define LIGHTPURPLE_GREEN             0x2d
#define LIGHTYELLOW_GREEN             0x2e
#define BRIGHTWHITE_GREEN             0x2f
#define BLACK_AQUA                    0x30
#define BLUE_AQUA                     0x31
#define GREEN_AQUA                    0x32
#define AQUA_AQUA                     0x33
#define RED_AQUA                      0x34
#define PURPLE_AQUA                   0x35
#define YELLOW_AQUA                   0x36
#define WHITE_AQUA                    0x37
#define GREY_AQUA                     0x38
#define LIGHTBLUE_AQUA                0x39
#define LIGHTGREEN_AQUA               0x3a
#define LIGHTAQUA_AQUA                0x3b
#define LIGHTRED_AQUA                 0x3c
#define LIGHTPURPLE_AQUA              0x3d
#define LIGHTYELLOW_AQUA              0x3e
#define BRIGHTWHITE_AQUA              0x3f
#define BLACK_RED                     0x40
#define BLUE_RED                      0x41
#define GREEN_RED                     0x42
#define AQUA_RED                      0x43
#define RED_RED                       0x44
#define PURPLE_RED                    0x45
#define YELLOW_RED                    0x46
#define WHITE_RED                     0x47
#define GREY_RED                      0x48
#define LIGHTBLUE_RED                 0x49
#define LIGHTGREEN_RED                0x4a
#define LIGHTAQUA_RED                 0x4b
#define LIGHTRED_RED                  0x4c
#define LIGHTPURPLE_RED               0x4d
#define LIGHTYELLOW_RED               0x4e
#define BRIGHTWHITE_RED               0x4f
#define BLACK_PURPLE                  0x50
#define BLUE_PURPLE                   0x51
#define GREEN_PURPLE                  0x52
#define AQUA_PURPLE                   0x53
#define RED_PURPLE                    0x54
#define PURPLE_PURPLE                 0x55
#define YELLOW_PURPLE                 0x56
#define WHITE_PURPLE                  0x57
#define GREY_PURPLE                   0x58
#define LIGHTBLUE_PURPLE              0x59
#define LIGHTGREEN_PURPLE             0x5a
#define LIGHTAQUA_PURPLE              0x5b
#define LIGHTRED_PURPLE               0x5c
#define LIGHTPURPLE_PURPLE            0x5d
#define LIGHTYELLOW_PURPLE            0x5e
#define BRIGHTWHITE_PURPLE            0x5f
#define BLACK_YELLOW                  0x60
#define BLUE_YELLOW                   0x61
#define GREEN_YELLOW                  0x62
#define AQUA_YELLOW                   0x63
#define RED_YELLOW                    0x64
#define PURPLE_YELLOW                 0x65
#define YELLOW_YELLOW                 0x66
#define WHITE_YELLOW                  0x67
#define GREY_YELLOW                   0x68
#define LIGHTBLUE_YELLOW              0x69
#define LIGHTGREEN_YELLOW             0x6a
#define LIGHTAQUA_YELLOW              0x6b
#define LIGHTRED_YELLOW               0x6c
#define LIGHTPURPLE_YELLOW            0x6d
#define LIGHTYELLOW_YELLOW            0x6e
#define BRIGHTWHITE_YELLOW            0x6f
#define BLACK_WHITE                   0x70
#define BLUE_WHITE                    0x71
#define GREEN_WHITE                   0x72
#define AQUA_WHITE                    0x73
#define RED_WHITE                     0x74
#define PURPLE_WHITE                  0x75
#define YELLOW_WHITE                  0x76
#define WHITE_WHITE                   0x77
#define GREY_WHITE                    0x78
#define LIGHTBLUE_WHITE               0x79
#define LIGHTGREEN_WHITE              0x7a
#define LIGHTAQUA_WHITE               0x7b
#define LIGHTRED_WHITE                0x7c
#define LIGHTPURPLE_WHITE             0x7d
#define LIGHTYELLOW_WHITE             0x7e
#define BRIGHTWHITE_WHITE             0x7f
#define BLACK_GREY                    0x80
#define BLUE_GREY                     0x81
#define GREEN_GREY                    0x82
#define AQUA_GREY                     0x83
#define RED_GREY                      0x84
#define PURPLE_GREY                   0x85
#define YELLOW_GREY                   0x86
#define WHITE_GREY                    0x87
#define GREY_GREY                     0x88
#define LIGHTBLUE_GREY                0x89
#define LIGHTGREEN_GREY               0x8a
#define LIGHTAQUA_GREY                0x8b
#define LIGHTRED_GREY                 0x8c
#define LIGHTPURPLE_GREY              0x8d
#define LIGHTYELLOW_GREY              0x8e
#define BRIGHTWHITE_GREY              0x8f
#define BLACK_LIGHTBLUE               0x90
#define BLUE_LIGHTBLUE                0x91
#define GREEN_LIGHTBLUE               0x92
#define AQUA_LIGHTBLUE                0x93
#define RED_LIGHTBLUE                 0x94
#define PURPLE_LIGHTBLUE              0x95
#define YELLOW_LIGHTBLUE              0x96
#define WHITE_LIGHTBLUE               0x97
#define GREY_LIGHTBLUE                0x98
#define LIGHTBLUE_LIGHTBLUE           0x99
#define LIGHTGREEN_LIGHTBLUE          0x9a
#define LIGHTAQUA_LIGHTBLUE           0x9b
#define LIGHTRED_LIGHTBLUE            0x9c
#define LIGHTPURPLE_LIGHTBLUE         0x9d
#define LIGHTYELLOW_LIGHTBLUE         0x9e
#define BRIGHTWHITE_LIGHTBLUE         0x9f
#define BLACK_LIGHTGREEN              0xa0
#define BLUE_LIGHTGREEN               0xa1
#define GREEN_LIGHTGREEN              0xa2
#define AQUA_LIGHTGREEN               0xa3
#define RED_LIGHTGREEN                0xa4
#define PURPLE_LIGHTGREEN             0xa5
#define YELLOW_LIGHTGREEN             0xa6
#define WHITE_LIGHTGREEN              0xa7
#define GREY_LIGHTGREEN               0xa8
#define LIGHTBLUE_LIGHTGREEN          0xa9
#define LIGHTGREEN_LIGHTGREEN         0xaa
#define LIGHTAQUA_LIGHTGREEN          0xab
#define LIGHTRED_LIGHTGREEN           0xac
#define LIGHTPURPLE_LIGHTGREEN        0xad
#define LIGHTYELLOW_LIGHTGREEN        0xae
#define BRIGHTWHITE_LIGHTGREEN        0xaf
#define BLACK_LIGHTAQUA               0xb0
#define BLUE_LIGHTAQUA                0xb1
#define GREEN_LIGHTAQUA               0xb2
#define AQUA_LIGHTAQUA                0xb3
#define RED_LIGHTAQUA                 0xb4
#define PURPLE_LIGHTAQUA              0xb5
#define YELLOW_LIGHTAQUA              0xb6
#define WHITE_LIGHTAQUA               0xb7
#define GREY_LIGHTAQUA                0xb8
#define LIGHTBLUE_LIGHTAQUA           0xb9
#define LIGHTGREEN_LIGHTAQUA          0xba
#define LIGHTAQUA_LIGHTAQUA           0xbb
#define LIGHTRED_LIGHTAQUA            0xbc
#define LIGHTPURPLE_LIGHTAQUA         0xbd
#define LIGHTYELLOW_LIGHTAQUA         0xbe
#define BRIGHTWHITE_LIGHTAQUA         0xbf
#define BLACK_LIGHTRED                0xc0
#define BLUE_LIGHTRED                 0xc1
#define GREEN_LIGHTRED                0xc2
#define AQUA_LIGHTRED                 0xc3
#define RED_LIGHTRED                  0xc4
#define PURPLE_LIGHTRED               0xc5
#define YELLOW_LIGHTRED               0xc6
#define WHITE_LIGHTRED                0xc7
#define GREY_LIGHTRED                 0xc8
#define LIGHTBLUE_LIGHTRED            0xc9
#define LIGHTGREEN_LIGHTRED           0xca
#define LIGHTAQUA_LIGHTRED            0xcb
#define LIGHTRED_LIGHTRED             0xcc
#define LIGHTPURPLE_LIGHTRED          0xcd
#define LIGHTYELLOW_LIGHTRED          0xce
#define BRIGHTWHITE_LIGHTRED          0xcf
#define BLACK_LIGHTPURPLE             0xd0
#define BLUE_LIGHTPURPLE              0xd1
#define GREEN_LIGHTPURPLE             0xd2
#define AQUA_LIGHTPURPLE              0xd3
#define RED_LIGHTPURPLE               0xd4
#define PURPLE_LIGHTPURPLE            0xd5
#define YELLOW_LIGHTPURPLE            0xd6
#define WHITE_LIGHTPURPLE             0xd7
#define GREY_LIGHTPURPLE              0xd8
#define LIGHTBLUE_LIGHTPURPLE         0xd9
#define LIGHTGREEN_LIGHTPURPLE        0xda
#define LIGHTAQUA_LIGHTPURPLE         0xdb
#define LIGHTRED_LIGHTPURPLE          0xdc
#define LIGHTPURPLE_LIGHTPURPLE       0xdd
#define LIGHTYELLOW_LIGHTPURPLE       0xde
#define BRIGHTWHITE_LIGHTPURPLE       0xdf
#define BLACK_LIGHTYELLOW             0xe0
#define BLUE_LIGHTYELLOW              0xe1
#define GREEN_LIGHTYELLOW             0xe2
#define AQUA_LIGHTYELLOW              0xe3
#define RED_LIGHTYELLOW               0xe4
#define PURPLE_LIGHTYELLOW            0xe5
#define YELLOW_LIGHTYELLOW            0xe6
#define WHITE_LIGHTYELLOW             0xe7
#define GREY_LIGHTYELLOW              0xe8
#define LIGHTBLUE_LIGHTYELLOW         0xe9
#define LIGHTGREEN_LIGHTYELLOW        0xea
#define LIGHTAQUA_LIGHTYELLOW         0xeb
#define LIGHTRED_LIGHTYELLOW          0xec
#define LIGHTPURPLE_LIGHTYELLOW       0xed
#define LIGHTYELLOW_LIGHTYELLOW       0xee
#define BRIGHTWHITE_LIGHTYELLOW       0xef
#define BLACK_BRIGHTWHITE             0xf0
#define BLUE_BRIGHTWHITE              0xf1
#define GREEN_BRIGHTWHITE             0xf2
#define AQUA_BRIGHTWHITE              0xf3
#define RED_BRIGHTWHITE               0xf4
#define PURPLE_BRIGHTWHITE            0xf5
#define YELLOW_BRIGHTWHITE            0xf6
#define WHITE_BRIGHTWHITE             0xf7
#define GREY_BRIGHTWHITE              0xf8
#define LIGHTBLUE_BRIGHTWHITE         0xf9
#define LIGHTGREEN_BRIGHTWHITE        0xfa
#define LIGHTAQUA_BRIGHTWHITE         0xfb
#define LIGHTRED_BRIGHTWHITE          0xfc
#define LIGHTPURPLE_BRIGHTWHITE       0xfd
#define LIGHTYELLOW_BRIGHTWHITE       0xfe
#define BRIGHTWHITE_BRIGHTWHITE       0xff

#endif //WIN_CONSOLE_COLORS_H